# Generated by Django 4.0.3 on 2022-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], default=1),
        ),
    ]
