# Generated by Django 4.0.3 on 2022-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], default=0),
        ),
    ]
