# Generated by Django 4.0.3 on 2022-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
