# Generated by Django 4.0.3 on 2022-03-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_deal_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
