# Generated by Django 4.0.3 on 2022-03-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
