# Generated by Django 4.0.3 on 2022-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', max_length=30),
        ),
    ]
